version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: packing_sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password123!", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  packingservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: packing_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PackingDb;User Id=sa;Password=Password123!;
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy