#version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      MS_PASSWORD: "P4ssword@#2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U MS -P P4ssword@#2025 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build: .
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PackingDb;User=MS;Password=P4ssword@#2025;
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "sleep 20 && dotnet ef database update --no-build --project PackingService.Api/PackingService.Api.csproj && dotnet PackingService.Api.dll"
    ports:
      - "8080:8080"