version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P4ssword@#2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P \"P4ssword@#2025\" -Q \"SELECT 1\""]
      interval: 10s
      timeout: 5s
      retries: 10

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - ./:/src:cached
    environment:
      # garante que o shim do dotnet-ef e o dotnet SDK estejam no PATH
      DOTNET_ROOT: /usr/share/dotnet
      PATH: "/root/.dotnet/tools:/usr/share/dotnet:/usr/local/bin:/usr/bin:/bin"
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - bash
      - -lc
      - |
        set -e
        echo "1) Instalando/verificando dotnet-ef..."
        dotnet tool install --global dotnet-ef --version 9.0.5
        echo "2) Atualizando PATH para incluir ~/.dotnet/tools"
        export PATH="$PATH:$HOME/.dotnet/tools"
        echo "PATH é: $PATH"
        echo "3) Executando migrations..."
        dotnet ef database update --project PackingService.Api/PackingService.Api.csproj
        echo "Migrations concluídas com sucesso."

  api:
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=PackingDb;User Id=sa;Password=P4ssword@#2025;TrustServerCertificate=true;"
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
